# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#  vmImage: ubuntu-latest

pool:
      name: Default
      Demands:
      - agent.name -equals "michal-ubuntu-w"

steps:
- task: CmdLine@2
  inputs:
    script: 'cat -A /home/michal/myagent/_work/1/s/broken.ts'
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SQ8'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'broken'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.verbose=true


- task: SonarQubeAnalyze@5